name: Deploy test
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: echo dev
        run: echo ${{ github.sha }}
#test
  deployint:
    needs: build
    environment:
      name: int
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: echo int
        run: echo ${{ github.sha }}
  deploystaging:
    needs: deployint
    environment:
      name: staging
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: echo int
        run: ec3t3t4t4ho ${{ github.sha }}
  deployprod:
    needs: deploystaging
    environment:
      name: prod
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: echo int
        run: echo ${{ github.sha }}
